services:
  back:
    image: backend_image
    build:
      context: .
    hostname: backend
    container_name: backend
    volumes:
      - ./financial_data.db:/app/financial_data.db
      - ./app.py:/app/app.py
      - ./db.py:/app/db.py
      - ../huobi:/app/huobi
    environment:
      PYTHONPATH: "/app"
    ports:
      - "80:5000"
    command: ['gunicorn', '-w', '4', '-b', '0.0.0.0:5000', 'app:server']